#!/usr/bin/env bash
# Configures a ufw firewall to block all incoming traffic
#+ except for TCP ports 22, 443 and 80.

ssh JERRI-STAR@92550-web-01
sudo apt-get update
sudo apt-get install ufw
sudo ufw enable
sudo ufw start
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw status
